Document: cryptopp
Title: Debian cryptopp Manual
Author: <insert document author here>
Abstract: This manual describes what cryptopp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cryptopp/cryptopp.sgml.gz

Format: postscript
Files: /usr/share/doc/cryptopp/cryptopp.ps.gz

Format: text
Files: /usr/share/doc/cryptopp/cryptopp.text.gz

Format: HTML
Index: /usr/share/doc/cryptopp/html/index.html
Files: /usr/share/doc/cryptopp/html/*.html
